//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        public string MNumber { get; set; }
        public string InterviewCompany { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public Nullable<bool> Offer { get; set; }
    
        public virtual User User { get; set; }
    }
}
